name: flutter_ui
description: A place where I try to re-create UI's I find interesting from social media posts.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_container: ^0.0.4
  timeline_tile: ^2.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 900